# PID of current job: 16792
mSet<-InitDataObjects("conc", "pathora", FALSE)
cmpd.vec<-c("ANTHRANILATE","GLYCYL-L-LEUCINE","CYTIDINE","ISOCYTOSINE","ETHANOLAMINE PHOSPHATE","GUANOSINE 5'-MONOPHOSPHATE","URIDINE-5-MONOPHOSPHATE","D-RIBOSE","CREATINE","GLUCOSAMINE/MANNOSAMINE","PUTRESCINE","URACIL","CARNOSINE","CYTOSINE","AGMATINE SULFATE","GLYCEROPHOSPHOCHOLINE","L-GLUTAMINE","L-CYSTINE","L-PROLINE","ALDO/KETO-HEXOSE","L-CYSTEINE","6C-SUGAR ALCOHOL","URIDINE","5-AMINOLEVULINIC ACID","UROCANATE","ADENOSINE 5'-MONOPHOSPHATE","L-SERINE","4-AMINOBUTANOATE (GABA)","ORTHOPHOSPHATE","N-ALPHA-ACETYL-L-LYSINE","D-(+)-GALACTOSAMINE","ALPHA-AMINOADIPATE/N-METHYL-L-GLUTAMATE","L-ASPARAGINE","ORNITHINE","DL-5-HYDROXYLYSINE","NICOTINATE","L-LYSINE","CITRULLINE","N-ACETYL-ARGININE","PYRIDOXINE","HISTAMINE","PIPECOLATE/L-PIPECOLIC ACID","L-ISOLEUCINE","CREATININE","GLYCINE","DOPAMINE","5-OXO-L-PROLINE","L-CYSTATHIONINE","TAURINE","3-METHYL-2-OXINDOLE","L-METHIONINE","L-CARNITINE","N-ACETYLPUTRESCINE","L-KYNURENINE","SARMENTOSIN","N6,N6-DIMETHYLADENOSINE","PYROCOLL","N2-ACETYL-L-AMINOADIPATE","N-CARBAMOYLPUTRESCINE","VALYVALINE","HARMAN","PIPERIDINE","NORHARMAN","?-CARBOLINE","HYDROXYPENTOBARBITAL","5-NITRO-ORTHO-ANISIDINE","8-HYDROXYLANYLCLAVAM","ENTERODIOL SULFATE","(2S,4S)-MONATIN","PRENYL-L-CYSTEINE","LEU-GLY-PRO","8-HYDROXYPURINE","N-LACTOYL-TRYPTOPHAN","OZAGREL","ETHIRIMOL","MACULOSIN","AMPICILLIN","OXOARGININE","TULOBUTEROL","PYROGLUTAMYLGLYCINE","SULPHO NONOATE","DEOXYCYTIDINE","L-FORMYLKYNURENINE","ISOCARBAMID","ZALCITABINE","METHARBITAL","ECTOINE","APROBARBITAL","BARBITAL","ETOMIDATE","HOMOCITRULLINE","METHOXYBRASSININ","PYROGLUTMYLGLYCINE","BIOTIN","5-AMINOPENTANAMIDE","LYXOSYLAMINE","PIRBUTEROL","HEPTANOYLCHOLINE","OROTIC ACID")
mSet<-Setup.MapData(mSet, cmpd.vec);
mSet<-CrossReferencing(mSet, "name");
mSet<-CreateMappingResultTable(mSet)
mSet<-SetKEGG.PathLib(mSet, "hsa", "current")
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
mSet<-PlotPathSummary(mSet, F, "path_view_0_", "png", 72, width=NA, NA, NA )
mSet<-SetKEGG.PathLib(mSet, "ppu", "current")
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
mSet<-PlotPathSummary(mSet, F, "path_view_1_", "png", 72, width=NA, NA, NA )
