# PID of current job: 3359862
mSet<-InitDataObjects("conc", "pathora", FALSE)
cmpd.vec<-c("N-METHYL-L-GLUTAMATE","GLYCEROL 2-PHOSPHATE","PANTETHEINE","MALATE","2-AMINOETHYL DIHYDROGEN PHOSPHATE","N-ACETYL-HEXOSAMINE","URIDINE-5-MONOPHOSPHATE","N-ACETYL-D-MANNOSAMINE","XANTHINE","URACIL","ALDOPENTOSE","HYPOXANTHINE","L-CYSTEINE-S-SULFATE","CMP","D-GLUCURONIC ACID","CYTIDINE","L-GLUTAMINE","GUANOSINE 5'-MONOPHOSPHATE","L-HISTIDINE","5-AMINOLEVULINIC ACID","URIDINE","L-SERINE","1,2-BENZISOTHIAZOLIN-3-ONE","D-RIBOSE 5-PHOSPHATE","HEXOSE","N-ACETYL-L-ASPARTIC ACID","3-(2-HYDROXYPHENYL)PROPANOATE","UROCANATE","LL-2,6-DIAMINOHEPTANEDIOATE","ALPHA-AMINOADIPATE","CITRULLINE","ASPARAGINE","ADENOSINE 5'-MONOPHOSPHATE","L-KYNURENINE","CARNOSINE","PYRIDOXINE","2,3-DIHYDROXYISOVALERATE","4-OXOPROLINE","FRUCTOSE","DL-5-HYDROXYLYSINE","PROLINE","PANTOTHENIC ACID","SUCCINATE","3-SULFINO-L-ALANINE","GLUCOSE","L-METHIONINE","CITRAMALATE","TAURINE","N-ACETYL-L-ALANINE","DISACCHARIDE","INDOLE-3-ACETATE","L-CYSTATHIONINE","XYLENESULFONATE","GLUTARATE","L-CYSTEIC ACID","SARMENTOSIN","SULFATE","SULFONIC ACID","8-HYDROXYPURINE","DESACETYLCEFOTAXIME","GLYCYLPROLYLHYDROXYPROLINE","CARBOXYLIC ACID","L-ORNITHINE","N-HISTIDINE","GLYCEROL","GLYCEROPHOSPHOINOSITOL","HYDROXYAMINALINE","2-OXOARGININE","PENMACRIC ACID","PROPANOIC ACID","SACCHAROPINE","P-TOLUENESULFONIC ACID","PYROGLUTAMYLGLYCINE","N-NONANOYLGLYCINE","PHENYLALANYL","DIMETHOXYQUINAZOLINE","CYCLOBRASSINONE","TRIHYDROXYOXANE-2-CARBOXYLIC ACID","7-OXABICYCLO[4.1.0]HEPT-3-ENE-2,5-DIONE","PURINE","BETA-CARBOLINE-3-CARBOXYLIC ACID","R-138727(PRASUGREL)","POTASSIUM 2-(1'-ETHOXY) ETHOXYPROPANOATE","URIDINE 2',3'-CYCLIC PHOSPHATE")
mSet<-Setup.MapData(mSet, cmpd.vec);
mSet<-CrossReferencing(mSet, "name");
mSet<-CreateMappingResultTable(mSet)
mSet<-SetKEGG.PathLib(mSet, "hsa", "current")
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
mSet<-PlotPathSummary(mSet, F, "path_view_0_", "png", 72, width=NA, NA, NA )
mSet<-SetKEGG.PathLib(mSet, "ppu", "current")
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
mSet<-PlotPathSummary(mSet, F, "path_view_1_", "png", 72, width=NA, NA, NA )
